language: cpp
dist: xenial

addons:
  apt:
    packages:
      - g++
      - clang
      - cmake
      - libtbb-dev
      - libcurl4-openssl-dev
      - libace-dev
      - libmysql++-dev
      
  install:
    - export TBB_ROOT_DIR=/usr/include/tbb/
    - export ACE_ROOT=/usr/include/ace/
    
matrix:
  include:
    #linux builds on gcc x64
    - os: linux
      arch: amd64
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
    #linux builds on clang x64 
    - os: linux
      arch: amd64
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
scripts: |-
     mkdir build
     cd build
     cmake -DDEBUG=0 -DUSE_LIBCURL=1 ..
     make -j$(nproc)
        
